_BASE_: Base-PointRend-RCNN-FPN.yaml
MODEL:
  # WEIGHTS: ./output_new/model_final.pth
  WEIGHTS: detectron2://ImageNetPretrained/MSRA/R-101.pkl
  MASK_ON: true
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 1
    IOU_THRESHOLDS:
      - 0.5
  POINT_HEAD:
    NUM_CLASSES: 1
    SUBDIVISION_STEPS: 7
    TRAIN_NUM_POINTS: 256
    SUBDIVISION_NUM_POINTS: 1024
  SEM_SEG_HEAD:
    NUM_CLASSES: 1
    LOSS_WEIGHT: 3.0
  RPN:
    LOSS_WEIGHT: 5.0
  RETINANET:
    NUM_CLASSES: 1
  
SOLVER:
  MAX_ITER: 30000
  BASE_LR: 0.02
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 1000
  STEPS:
    - 2000
    - 4000
    - 6000
    - 20000
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 500
  WARMUP_METHOD: linear
  IMS_PER_BATCH: 16
INPUT:
  # Size of the smallest side of the image during training
  MIN_SIZE_TRAIN: (384, 512, 768)
  # Sample size of smallest side by choice or random selection from range give by
  # INPUT.MIN_SIZE_TRAIN
  # Maximum size of the side of the image during training
  MAX_SIZE_TRAIN: 1024
# To add COCO AP evaluation against the higher-quality LVIS annotations.
# DATASETS:
#   TEST: ("coco_2017_val", "lvis_v0.5_val_cocofied")
DATASETS:
  TRAIN: ("large_hair_train",)
  TEST: ("large_hair_val",)
DATALOADER:
  NUM_WORKERS: 4

OUTPUT_DIR: ./output_ins
